exports.paginaInicial = function(){
    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About People...</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Arquivo de Pessoas</h1>
            </header>
            <ul class="w3-ul w3-border">
                <li><h2>Lista de opções disponíveis</h2></li>
                <li><a href="listar_pessoas"> Lista de Pessoas </a></li>
                <li><a href="listar_sexo"> Distribuição por sexo </a></li>
                <li><a href="listar_desporto"> Distribuição por desporto </a></li>
                <li><a href="listar_top10"> Top 10 de profissões </a></li>
            </ul>
            <footer class="w3-container w3-teal">
                <h5>Generated by AROM98 @ RPCW23</h5>
            </footer>
        </div>
    </body>
</html>
    `
    return pagHTML;
}


exports.listaPessoas = function(lista){
    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About People...</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Lista de Pessoas</h1>
            </header>

            <div class="w3-container">
                <table class="w3-table-all w3-hoverable" border="1">
                <tr>
                    <th>Id</th><th>Nome</th><th>Idade</th><th>Sexo</th><th>Cidade</th>
                </tr>
    `
    for (let i = 0; i < lista.length; i++) {
        pagHTML += `
        <a href="pessoa/${lista[i].id}">
            <tr onclick="location.href='/pessoa/${lista[i].id}';">
                <td>${lista[i].id}</td>
                <td>${lista[i].nome}</td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
            </tr>
        </a>
        `
    }

    pagHTML += `
        </table>
    </div>
    <footer class="w3-container w3-teal">
        <h5>Generated by AROM98 @ RPCW23</h5>
    </footer>
    </div>
    </body>
</html>
    `
    return pagHTML;
}


exports.listaSexo = function(lista){
    //count amount of each sex
    var countM = 0;
    var countF = 0;
    var countO = 0;
    for (let i = 0; i < lista.length; i++) {
        if(lista[i].sexo == "masculino"){
            countM++;
        }else if(lista[i].sexo == "feminino"){
            countF++;
        }else{
            countO++;
        }
    }


    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About People...</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Arquivo de Pessoas</h1>
            </header>
            <ul class="w3-ul w3-border">
                <li><h2>Listagem por sexo</h2></li>
                <li><a href="listar_sexo/masculino"> sexo masculino - ${countM} elementos </a></li>
                <li><a href="listar_sexo/feminino"> sexo feminino - ${countF} elementos </a></li>
                <li><a href="listar_sexo/outro"> outro - ${countO} elementos </a></li>
            </ul>
            <footer class="w3-container w3-teal">
                <h5>Generated by AROM98 @ RPCW23</h5>
            </footer>
        </div>
    </body>
</html>
    `
    return pagHTML;
}


exports.listaDesporto = function(lista){
    //count amount of each sport
    var desportos_final = {};
    for (let i = 0; i < lista.length; i++) {
        // lista[i].desporto is a list of sports
        // cheack if if lista[i] has desportos
        desp = lista[i].desportos;
        for (let j = 0; j < desp.length; j++) {
            if(desportos_final[desp[j]]){
                desportos_final[desp[j]]++;
            }else{
                desportos_final[desp[j]] = 1;
            }
        }
    }

    // ordenar desportos por ordem decrescente de frequencia
    var desportos_ordenados = {};
    Object.keys(desportos_final).sort(function(a,b){return desportos_final[b]-desportos_final[a]}).forEach(function(v){desportos_ordenados[v]=desportos_final[v]})


    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About People...</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Arquivo de Pessoas</h1>
            </header>
            <ul class="w3-ul w3-border">
                <li><h2>Listagem por desporto</h2></li>
`
    for (var key in desportos_ordenados) {
        pagHTML += `
        <li><a href="listar_desporto/${key}"> ${key} ---- ${desportos_ordenados[key]} elementos </a></li>
        `
    }
pagHTML += `  
            </ul>
            <footer class="w3-container w3-teal">
                <h5>Generated by AROM98 @ RPCW23</h5>
            </footer>
        </div>
    </body>
</html>
    `
    return pagHTML;
}



exports.listaTop10 = function(lista){
    // count amount of each profession
    var professions = {};
    for (let i = 0; i < lista.length; i++) {
        if(professions[lista[i].profissao]){
            professions[lista[i].profissao]++;
        }else{
            professions[lista[i].profissao] = 1;
        }
    }

    // ordenar desportos por ordem decrescente de frequencia
    var professions_ordenados = {};
    Object.keys(professions).sort(function(a,b){return professions[b]-professions[a]}).forEach(function(v){professions_ordenados[v]=professions[v]})
    // get top 10
    var top10 = {};
    var i = 0;
    for (var key in professions_ordenados) {
        if(i < 10){
            top10[key] = professions_ordenados[key];
        }
        i++;
    }
    

    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About People...</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Arquivo de Pessoas</h1>
            </header>
            <ul class="w3-ul w3-border">
                <li><h2>Top 10 de profissões</h2></li>
`
    for (var key in top10) {
        pagHTML += `
        <li><a href="listar_desporto/${key}"> ${key} ---- ${top10[key]} elementos </a></li>
        `
    }
pagHTML += `  
            </ul>
            <footer class="w3-container w3-teal">
                <h5>Generated by AROM98 @ RPCW23</h5>
            </footer>
        </div>
    </body>
</html>
    `
    return pagHTML;
}

